permissions:
  BETTER_BONEMEAL:
    name: "Vylepšená Kostní Moučka"
    lore: "Bonemeal který se dá použít na Cactus a Sugar Cane"
    permission: "aeterum.demeter.bonemeal"
    custom_id: 60001
    material: "BONE_MEAL"
  GROWTH_POTION:
    name: "Lektvar Růstu"
    lore: "Lektvar který urychlý růst rostlin v okolí hráče"
    permission: "aeterum.demeter.growth_potion"
    custom_id: 60002
    material: "HONEY_BOTTLE"
    recipe_potion: regeneration
    color:
      red: 63
      green: 206
      blue: 130
  HOE_OF_THE_HARVEST:
    name: "Kosa Úrody"
    lore: "Jestli-že někdo vý jak farmařit tak jsi to ty."
    permission: "aeterum.demeter.hoe"
    custom_id: 60003
    material: "NETHERITE_HOE"
  FLOWER_HORSE_TAME:
    name: "Démétéřin Roh"
    lore: "Zatrub a přivolej svého koně"
    permission: "aeterum.demeter.horse_tame"
    custom_id: 60004
    material: "GOAT_HORN"
  FLOWER_HORSE_ABILITY:
    name: "Horse Ability"
    permission: "aeterum.demeter.horse_ability"
  DEMETER_GUI:
    name: "GUI"
    permission: "aeterum.demeter.gui"
  PARTY_ATMOSPHERE:
    name: "Party Atmosféra"
    lore: Let's Party!!!
    permission: "aeterum.dionysus.party_atmosphere"
    custom_id: 60013
    material: "HONEY_BOTTLE"
    color:
      red: 255
      green: 185
      blue: 54
  PARTY_BALL:
    name: "Party Koule"
    lore: "Pozor na výbuch"
    permission: "aeterum.dionysus.party_ball"
    custom_id: 60012
    material: "SNOWBALL"
  RANDOM_EFFECT_POTION:
    name: "Záhadný Nápoj"
    lore: "Kdo vý co se může stát"
    permission: "aeterum.dionysus.random_effect_potion"
    custom_id: 60014
    material: "HONEY_BOTTLE"
    color:
      red: 43
      green: 158
      blue: 54
  DRUNK_HORSE_TAME:
    name: "Dionýsův Roh"
    lore: "Zatrub a přivolej svého koně"
    permission: "aeterum.dionysus.horse_tame"
    custom_id: 60006
    material: "GOAT_HORN"
  DRUNK_HORSE_ABILITY:
    name: "Horse Ability"
    permission: "aeterum.dionysus.horse_ability"
  DIONYSUS_GUI:
    name: "GUI"
    permission: "aeterum.dionysus.gui"
  DARKNESS_POTION:
    name: "Temný Lektvar"
    lore: "Oslep své nepřátele"
    permission: "aeterum.hades.darkness_potion"
    custom_id: 60016
    material: "HONEY_BOTTLE"
    color:
      red: 16
      green: 41
      blue: 84
  DARK_PEARL:
    name: "Temná Perla"
    lore: "Prostě Ender Pearl. Možná trochu lepší."
    permission: "aeterum.hades.dark_pearl"
    custom_id: 60017
    material: "ENDER_PEARL"
  DARK_PORTAL:
    name: "Temný Portál"
    lore: "Kde se objevíš?"
    permission: "aeterum.hades.portal"
    custom_id: 60018
    material: "SPLASH_POTION"
    color:
      red: 57
      green: 16
      blue: 84
  ZOMBIE_HORSE_TAME:
    name: "Hádesův Roh"
    lore: "Zatrub a přivolej svého koně"
    permission: "aeterum.hades.horse_tame"
    custom_id: 60005
    material: "GOAT_HORN"
  ZOMBIE_HORSE_ABILITY:
    name: "Horse Ability"
    permission: "aeterum.hades.horse_ability"
  HADES_COMMAND:
    name: "Nightvision"
    permission: "aeterum.hades.command"
  HADES_GUI:
    name: "GUI"
    permission: "aeterum.hades.gui"
  FLYING_ITEM:
    name: "Nekonečná Raketka"
    lore: "Málo raketek? Použij toto."
    permission: "aeterum.hermes.flying_item"
    custom_id: 60019
    material: "STONE_SWORD"
  MESSENGER_PACK:
    name: "Poštovní Brašna"
    lore: "Bůh zpráv potřebuje pořádnou brašnu"
    permission: "aeterum.hermes.messenger_pack"
    custom_id: 60020
    material: "PLAYER_HEAD"
  SPEED_BOOTS:
    name: "Rychlé botky"
    lore: "Tyhle botky vypadají rychle. Nezakopni."
    permission: "aeterum.hermes.speed_boots"
    custom_id: 60021
    material: "IRON_BOOTS"
  SPEED_HORSE_TAME:
    name: "Hermesův Roh"
    lore: "Zatrub a přivolej svého koně"
    permission: "aeterum.hermes.horse_tame"
    custom_id: 60007
    material: "GOAT_HORN"
    recipe_potion: swiftness
  SPEED_HORSE_ABILITY:
    name: "Lektvar Rychlích Kopit"
    lore: "Sedni na svého koně, napij se a drž se"
    permission: "aeterum.hermes.horse_ability"
    custom_id: 60008
    material: "HONEY_BOTTLE"
    color:
      red: 193
      green: 193
      blue: 193
  HERMES_GUI:
    name: "GUI"
    permission: "aeterum.hermes.gui"
  SEA_HORSE_TAME:
    name: "Poseidonův Roh"
    lore: "Zatrub a přivolej svého koně"
    permission: "aeterum.poseidon.horse_tame"
    custom_id: 60009
    material: "GOAT_HORN"
  SEA_HORSE_ABILITY:
    name: "Horse Ability"
    permission: "aeterum.poseidon.horse_ability"
  WATER_BREATHING_CROWN:
    name: "Mořská Koruna"
    lore: "Pomáhá dýchat pod vodou."
    permission: "aeterum.poseidon.crown"
    custom_id: 60023
    material: "TURTLE_HELMET"
  BETTER_TRIDENT:
    name: "Královský Trojzubec"
    lore: "Zbraň hodná krále moří"
    permission: "aeterum.poseidon.trident"
    custom_id: 60022
    material: "TRIDENT"
  POSEIDON_COMMAND:
    name: "Dolphingrace"
    permission: "aeterum.poseidon.command"
  POSEIDON_GUI:
    name: "GUI"
    permission: "aeterum.poseidon.gui"
  PEGASUS_HORSE_TAME:
    name: "Diův Roh"
    lore: "Zatrub a přivolej svého koně"
    permission: "aeterum.zeus.horse_tame"
    custom_id: 60010
    material: "GOAT_HORN"
  PEGASUS_HORSE_ABILITY:
    name: "Lektvar Levitujících Kopit"
    lore: "Napij se když si na svém koni"
    permission: "aeterum.zeus.horse_ability"
    custom_id: 60011
    material: "HONEY_BOTTLE"
    color:
      red: 204
      green: 205
      blue: 208
  BREEDING_ITEM:
    name: "Afrodisiakum"
    lore: "Nakrm zvíře"
    permission: "aeterum.zeus.breeding_item"
    custom_id: 60024
    material: "SLIME_BALL"
  LIGHTNING_SPEAR:
    name: "Blesk"
    lore: "Zbraň hodná hrále Olympu"
    permission: "aeterum.zeus.lightning_spear"
    custom_id: 60025
    material: "TRIDENT"
  WEATHER_CHANGER:
    name: "Lektvar Bouře"
    lore: "Moc slunečno? Tohle by mohlo být řešení"
    permission: "aeterum.zeus.weather_changer"
    custom_id: 60026
    material: "HONEY_BOTTLE"
    color:
      red: 165
      green: 161
      blue: 215
  ZEUS_GUI:
    name: "GUI"
    permission: "aeterum.zeus.gui"
  RANDOMIZER:
    name: "Lopatka"
    lore: "Položí náhodný block z hotbaru"
    permission: "aeterum.trowel.use"
    custom_id: 60015
    material: "IRON_SHOVEL"